name: Check for typos

on:
  push:
    branches:
      - master
    paths:
      - 'java/**.java'
      - 'java/**.xml'
      - 'web/html/src/**'
      - '.github/workflows/typos.yml'
  pull_request:
    paths:
      - 'java/**.java'
      - 'java/**.xml'
      - 'web/html/src/**'
      - '.github/workflows/typos.yml'

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Prepare file with mistakes.
      run: echo "Finallizes" > file.txt
    - name: Test force pass with mistakes
      continue-on-error: true
      with:
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "Finalizes" > file.txt

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master
      with: 
        files: ./file.txt

    - name: Ignore implicit configuration file
      uses: crate-ci/typos@master
      with: 
        files: ./file.txt
        isolated: true     
